/**
 * Shared plumbing for the four snapshot generators (`generate-*.mjs`): the
 * renovate version stamp, the `src/data/` output path, the AUTO-GENERATED
 * banner, the symlink guard, and the write-and-log tail. Each generator keeps
 * only the part that differs: which renovate module it reads and how it shapes
 * the snapshot.
 *
 * Nothing here touches `renovate` at import time, so a generator can run its
 * symlink guard (and fail fast) even where Renovate is not installed.
 */
import { writeFile, lstat } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { createRequire } from "node:module";

/** Version of the installed `renovate` package (read on first use). */
export function renovateVersion() {
  return createRequire(import.meta.url)("renovate/package.json").version;
}

/** Absolute path of a committed snapshot under `src/data/`. */
export function snapshotPath(filename) {
  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../src/data", filename);
}

/** The banner every snapshot starts with; `name` is the `generate:<name>` script suffix. */
export function generatedHeader(name) {
  return `// AUTO-GENERATED by scripts/generate-${name}.mjs from renovate@${renovateVersion()}.
// Do not edit by hand. Run \`npm run generate:${name}\` to refresh.
`;
}

// Refuse to overwrite a symlink at the destination. A working tree where the
// generated file has been swapped for a symlink (deliberate or not) would
// otherwise let the write follow the link to an arbitrary location. Call it
// before the heavy renovate import so the failure is fast and independent of
// Renovate being installable.
export async function refuseIfSymlink(target) {
  try {
    const stat = await lstat(target);
    if (stat.isSymbolicLink()) {
      console.error(
        `refusing to write to ${path.relative(process.cwd(), target)}: destination is a symlink`,
      );
      process.exit(1);
    }
  } catch (err) {
    if (err && err.code !== "ENOENT") throw err;
  }
}

/** Write the snapshot and log `Wrote <summary> from renovate@<version> to <path>`. */
export async function writeGenerated(target, contents, summary) {
  await writeFile(target, contents);
  console.log(
    `Wrote ${summary} from renovate@${renovateVersion()} to ${path.relative(process.cwd(), target)}`,
  );
}
