#!/usr/bin/env node
/**
 * Snapshot Renovate's config option registry into src/data/options.generated.ts.
 *
 * The resulting file is committed to git. Runtime code in src/ never imports
 * the renovate package; this script is the one exception (it's a build-time
 * step). Regenerate after bumping the `renovate` devDependency.
 *
 * Source of truth: renovate/dist/config/options/index.js, which exports
 * `getOptions()` — an array of option definition objects. We snapshot only a
 * fixed subset of fields (see ALLOWED_KEYS below); unlisted fields (e.g.
 * `mergeable`, `patternMatch`, `additionalProperties`, `freeChoice`) are
 * intentionally dropped as not needed by the `renovate://option/{name}`
 * resource.
 */
import { writeFile, lstat } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { createRequire } from "node:module";

// Refuse to overwrite a symlink at the destination. A working tree where the
// generated file has been swapped for a symlink (deliberate or not) would
// otherwise let the write follow the link to an arbitrary location.
async function refuseIfSymlink(target) {
  try {
    const stat = await lstat(target);
    if (stat.isSymbolicLink()) {
      console.error(
        `refusing to write to ${path.relative(process.cwd(), target)}: destination is a symlink`,
      );
      process.exit(1);
    }
  } catch (err) {
    if (err && err.code !== "ENOENT") throw err;
  }
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_PATH = path.resolve(__dirname, "../src/data/options.generated.ts");

// Check before doing the heavy renovate import so the failure is fast and
// independent of Renovate being installable.
await refuseIfSymlink(OUT_PATH);

const require = createRequire(import.meta.url);
const renovatePkg = require("renovate/package.json");

const optionsModule = await import("renovate/dist/config/options/index.js");
const allOptions = optionsModule.getOptions();

// Fields to keep, in the order they'll appear in the generated object
// literal. `name` is handled separately — it becomes the record key.
const ALLOWED_KEYS = [
  "description",
  "type",
  "subType",
  "default",
  "allowedValues",
  "globalOnly",
  "supportedManagers",
  "supportedPlatforms",
  "experimental",
  "experimentalDescription",
  "deprecationMsg",
  "parents",
  "stage",
  "advancedUse",
  "cli",
  "env",
];

const entries = {};
for (const opt of allOptions) {
  const snapshot = {};
  for (const key of ALLOWED_KEYS) {
    if (opt[key] !== undefined) snapshot[key] = opt[key];
  }
  entries[opt.name] = snapshot;
}

const sorted = Object.fromEntries(
  Object.entries(entries).sort(([a], [b]) => a.localeCompare(b)),
);

const header = `// AUTO-GENERATED by scripts/generate-options.mjs from renovate@${renovatePkg.version}.
// Do not edit by hand. Run \`npm run generate:options\` to refresh.
`;

const body = `
export interface GeneratedOption {
  description?: string;
  type?: string;
  subType?: string;
  default?: unknown;
  allowedValues?: readonly unknown[];
  globalOnly?: boolean;
  supportedManagers?: readonly string[];
  supportedPlatforms?: readonly string[];
  experimental?: boolean;
  experimentalDescription?: string;
  deprecationMsg?: string;
  parents?: readonly string[];
  stage?: string;
  advancedUse?: boolean;
  cli?: boolean;
  env?: boolean;
}

export const RENOVATE_VERSION = ${JSON.stringify(renovatePkg.version)};

export const OPTIONS: Record<string, GeneratedOption> = ${JSON.stringify(sorted, null, 2)};

export const OPTION_NAMES: readonly string[] = Object.freeze(Object.keys(OPTIONS));
`;

await writeFile(OUT_PATH, header + body);
console.log(
  `Wrote ${Object.keys(sorted).length} options from renovate@${renovatePkg.version} to ${path.relative(process.cwd(), OUT_PATH)}`,
);
