#!/usr/bin/env node
/**
 * Snapshot Renovate's built-in presets into src/data/presets.generated.ts.
 *
 * The resulting file is committed to git. Runtime code in src/ never imports
 * the renovate package; this script is the one exception (it's a build-time
 * step). Regenerate after bumping the `renovate` devDependency.
 *
 * Source of truth: renovate/dist/config/presets/internal/index.js, which
 * assembles per-namespace preset maps into a `groups` object. We recreate the
 * same namespace → filename mapping here because Renovate doesn't export
 * `groups` publicly.
 */
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const renovatePkg = require("renovate/package.json");

const NAMESPACES = {
  abandonments: "abandonments.preset.js",
  config: "config.preset.js",
  customManagers: "custom-managers.preset.js",
  default: "default.preset.js",
  docker: "docker.preset.js",
  global: "global.preset.js",
  group: "group.preset.js",
  helpers: "helpers.preset.js",
  mergeConfidence: "merge-confidence.preset.js",
  monorepo: "monorepos.preset.js",
  packages: "packages.preset.js",
  preview: "preview.preset.js",
  replacements: "replacements.preset.js",
  schedule: "schedule.preset.js",
  security: "security.preset.js",
  workarounds: "workarounds.preset.js",
};

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_PATH = path.resolve(__dirname, "../src/data/presets.generated.ts");

const entries = {};
for (const [namespace, filename] of Object.entries(NAMESPACES)) {
  const mod = await import(`renovate/dist/config/presets/internal/${filename}`);
  if (!mod.presets) {
    throw new Error(`${filename} has no \`presets\` export`);
  }
  for (const [name, preset] of Object.entries(mod.presets)) {
    const fullName = `${namespace}:${name}`;
    const { description, ...body } = preset;
    // Renovate lets description be `string | string[]` (arrays render as
    // multi-line bullet lists in the docs). Normalize to a single string so
    // consumers don't have to branch.
    const normalized =
      description == null
        ? null
        : Array.isArray(description)
          ? description.join(" ")
          : description;
    entries[fullName] = {
      namespace,
      description: normalized,
      body,
    };
  }
}

const sorted = Object.fromEntries(
  Object.entries(entries).sort(([a], [b]) => a.localeCompare(b)),
);

const header = `// AUTO-GENERATED by scripts/generate-presets.mjs from renovate@${renovatePkg.version}.
// Do not edit by hand. Run \`npm run generate:presets\` to refresh.
`;

const body = `
export interface GeneratedPreset {
  namespace: string;
  description: string | null;
  body: Record<string, unknown>;
}

export const RENOVATE_VERSION = ${JSON.stringify(renovatePkg.version)};

export const PRESETS: Record<string, GeneratedPreset> = ${JSON.stringify(sorted, null, 2)};

export const PRESET_NAMES: readonly string[] = Object.freeze(Object.keys(PRESETS));
`;

await writeFile(OUT_PATH, header + body);
console.log(`Wrote ${Object.keys(sorted).length} presets from renovate@${renovatePkg.version} to ${path.relative(process.cwd(), OUT_PATH)}`);
