// AUTO-GENERATED by scripts/generate-migrations.mjs from renovate@44.115.10.
// Do not edit by hand. Run `npm run generate:migrations` to refresh.

export const RENOVATE_VERSION = "44.115.10";

export interface DeprecatedKeyEntry {
  /** Key as it appeared in old configs. */
  readonly oldKey: string;
  /** Current key that replaces it — plain renames only; custom migrations omit it. */
  readonly newKey?: string;
}

/**
 * Deprecated config keys. Sourced from Renovate's `MigrationsService`:
 * `renamedProperties` (plain renames, with `newKey`) plus every
 * `customMigrations` class flagged `deprecated` (value coercions such as
 * `stabilityDays` → `minimumReleaseAge`, structural rewrites such as
 * `fileMatch` → `managerFilePatterns`; no `newKey` — `migrate_config`
 * shows the replacement).
 */
export const DEPRECATED_KEYS: readonly DeprecatedKeyEntry[] = Object.freeze([
  {
    "oldKey": "adoptium-java",
    "newKey": "java-version"
  },
  {
    "oldKey": "aliases",
    "newKey": "registryAliases"
  },
  {
    "oldKey": "allowedPostUpgradeCommands",
    "newKey": "allowedCommands"
  },
  {
    "oldKey": "automergeMajor"
  },
  {
    "oldKey": "automergeMinor"
  },
  {
    "oldKey": "automergePatch"
  },
  {
    "oldKey": "azureAutoApprove",
    "newKey": "autoApprove"
  },
  {
    "oldKey": "baseBranch"
  },
  {
    "oldKey": "baseBranches",
    "newKey": "baseBranchPatterns"
  },
  {
    "oldKey": "compatibility"
  },
  {
    "oldKey": "customChangelogUrl",
    "newKey": "changelogUrl"
  },
  {
    "oldKey": "endpoints",
    "newKey": "hostRules"
  },
  {
    "oldKey": "excludedPackageNames",
    "newKey": "excludePackageNames"
  },
  {
    "oldKey": "exposeEnv",
    "newKey": "exposeAllEnv"
  },
  {
    "oldKey": "fetchReleaseNotes"
  },
  {
    "oldKey": "fileMatch"
  },
  {
    "oldKey": "gomodTidy"
  },
  {
    "oldKey": "ignoreNodeModules"
  },
  {
    "oldKey": "ignoreNpmrcFile"
  },
  {
    "oldKey": "includeForks"
  },
  {
    "oldKey": "keepalive",
    "newKey": "keepAlive"
  },
  {
    "oldKey": "lookupNameTemplate",
    "newKey": "packageNameTemplate"
  },
  {
    "oldKey": "managerBranchPrefix",
    "newKey": "additionalBranchPrefix"
  },
  {
    "oldKey": "masterIssue",
    "newKey": "dependencyDashboard"
  },
  {
    "oldKey": "masterIssueApproval",
    "newKey": "dependencyDashboardApproval"
  },
  {
    "oldKey": "masterIssueAutoclose",
    "newKey": "dependencyDashboardAutoclose"
  },
  {
    "oldKey": "masterIssueFooter",
    "newKey": "dependencyDashboardFooter"
  },
  {
    "oldKey": "masterIssueHeader",
    "newKey": "dependencyDashboardHeader"
  },
  {
    "oldKey": "masterIssueLabels",
    "newKey": "dependencyDashboardLabels"
  },
  {
    "oldKey": "masterIssueTitle",
    "newKey": "dependencyDashboardTitle"
  },
  {
    "oldKey": "multipleMajorPrs",
    "newKey": "separateMultipleMajor"
  },
  {
    "oldKey": "packageFiles"
  },
  {
    "oldKey": "packageName"
  },
  {
    "oldKey": "packagePattern"
  },
  {
    "oldKey": "packages"
  },
  {
    "oldKey": "pathRules"
  },
  {
    "oldKey": "pinVersions"
  },
  {
    "oldKey": "rebaseConflictedPrs"
  },
  {
    "oldKey": "rebaseStalePrs"
  },
  {
    "oldKey": "recreateClosed"
  },
  {
    "oldKey": "regexManagers",
    "newKey": "customManagers"
  },
  {
    "oldKey": "renovate-config-presets",
    "newKey": "renovate-config"
  },
  {
    "oldKey": "renovateFork"
  },
  {
    "oldKey": "requiredStatusChecks"
  },
  {
    "oldKey": "semanticPrefix"
  },
  {
    "oldKey": "separatePatchReleases",
    "newKey": "separateMinorPatch"
  },
  {
    "oldKey": "stabilityDays"
  },
  {
    "oldKey": "trustLevel"
  },
  {
    "oldKey": "unpublishSafe"
  },
  {
    "oldKey": "updateLockFiles"
  },
  {
    "oldKey": "upgradeInRange"
  },
  {
    "oldKey": "versionScheme",
    "newKey": "versioning"
  },
  {
    "oldKey": "versionStrategy"
  }
]);
