// AUTO-GENERATED by scripts/generate-migrations.mjs from renovate@44.30.3.
// Do not edit by hand. Run `npm run generate:migrations` to refresh.

export const RENOVATE_VERSION = "44.30.3";

export interface DeprecatedKeyEntry {
  /** Key as it appeared in old configs. */
  readonly oldKey: string;
  /** Current key that replaces it. */
  readonly newKey: string;
}

/**
 * Deprecated config keys with their current replacement. Sourced from
 * Renovate's `MigrationsService.renamedProperties` — the "RenamePropertyMigration"
 * subset only. Value coercions (e.g. `stabilityDays` → `minimumReleaseAge`)
 * and structural transformations are deliberately excluded; `migrate_config`
 * is the right tool for those.
 */
export const DEPRECATED_KEYS: readonly DeprecatedKeyEntry[] = Object.freeze([
  {
    "oldKey": "adoptium-java",
    "newKey": "java-version"
  },
  {
    "oldKey": "aliases",
    "newKey": "registryAliases"
  },
  {
    "oldKey": "allowedPostUpgradeCommands",
    "newKey": "allowedCommands"
  },
  {
    "oldKey": "azureAutoApprove",
    "newKey": "autoApprove"
  },
  {
    "oldKey": "baseBranches",
    "newKey": "baseBranchPatterns"
  },
  {
    "oldKey": "customChangelogUrl",
    "newKey": "changelogUrl"
  },
  {
    "oldKey": "endpoints",
    "newKey": "hostRules"
  },
  {
    "oldKey": "excludedPackageNames",
    "newKey": "excludePackageNames"
  },
  {
    "oldKey": "exposeEnv",
    "newKey": "exposeAllEnv"
  },
  {
    "oldKey": "keepalive",
    "newKey": "keepAlive"
  },
  {
    "oldKey": "lookupNameTemplate",
    "newKey": "packageNameTemplate"
  },
  {
    "oldKey": "managerBranchPrefix",
    "newKey": "additionalBranchPrefix"
  },
  {
    "oldKey": "masterIssue",
    "newKey": "dependencyDashboard"
  },
  {
    "oldKey": "masterIssueApproval",
    "newKey": "dependencyDashboardApproval"
  },
  {
    "oldKey": "masterIssueAutoclose",
    "newKey": "dependencyDashboardAutoclose"
  },
  {
    "oldKey": "masterIssueFooter",
    "newKey": "dependencyDashboardFooter"
  },
  {
    "oldKey": "masterIssueHeader",
    "newKey": "dependencyDashboardHeader"
  },
  {
    "oldKey": "masterIssueLabels",
    "newKey": "dependencyDashboardLabels"
  },
  {
    "oldKey": "masterIssueTitle",
    "newKey": "dependencyDashboardTitle"
  },
  {
    "oldKey": "multipleMajorPrs",
    "newKey": "separateMultipleMajor"
  },
  {
    "oldKey": "regexManagers",
    "newKey": "customManagers"
  },
  {
    "oldKey": "renovate-config-presets",
    "newKey": "renovate-config"
  },
  {
    "oldKey": "separatePatchReleases",
    "newKey": "separateMinorPatch"
  },
  {
    "oldKey": "versionScheme",
    "newKey": "versioning"
  }
]);
